/*
 * MX-64AR.h
 *
 * Created: 20/03/2019 11:00:00
 * Author:	Marek Kujawa
 */

#ifndef MX64AR_H
#define MX64AR_H

#define MX_START 0xFF // to indicate the starting point of serial message (2x)
#define MX_ALL_SERVOS 0xFE // to broadcast to all the connected servos

/* MX-64AR Control Table (EEPROM) */
#define MX_MODEL_NUMBER_L 0x00
#define MX_MODEL_NUMBER_H 0x01
#define MX_VERSION_OF_FIRMWARE 0x02
#define MX_ID 0x03
#define MX_BAUD_RATE 0x04
#define MX_RETURN_RELAY_TIME 0x05
#define MX_CW_ANGLE_LIMIT_L 0x06
#define MX_CW_ANGLE_LIMIT_H 0x07
#define MX_CCW_ANGLE_LIMIT_L 0x08
#define MX_CCW_ANGLE_LIMIT_H 0x09

#define MX_ANGLE_MODE_WHEEL 0x00
#define MX_ANGLE_MODE_MULTI_TURN_L 0xFF
#define MX_ANGLE_MODE_MULTI_TURN_H 0x0F

#define MX_MAX_TORQUE_L 0x0E
#define MX_MAX_TORQUE_H 0x0F
#define MX_STATUS_RETURN_LEVEL 0x10
#define MX_ALARM_LED 0x11
#define MX_ALARM_SHUTDOWN 0x12
#define MX_MULTI_TURN_OFFSET_L 0x14
#define MX_MULTI_TURN_OFFSET_H 0x15
#define MX_RESOLUTION_DIVIDER 0x16
/* MX-64AR Control Table (RAM) */
#define MX_TORQUE_ENABLE 0x18
#define MX_LED 0x19
#define MX_D_GAIN 0x1A
#define MX_I_GAIN 0x1B
#define MX_P_GAIN 0x1C
#define MX_GOAL_POSITION_L 0x1E
#define MX_GOAL_POSITION_H 0x1F
#define MX_MOVING_SPEED_L 0x20
#define MX_MOVING_SPEED_H 0x21
#define MX_TORQUE_LIMIT_L 0x22
#define MX_TORQUE_LIMIT_H 0x23
#define MX_PRESENT_POSITION_L 0x24
#define MX_PRESENT_POSITION_H 0x25
#define MX_PRESENT_SPEED_L 0x26
#define MX_PRESENT_SPEED_H 0x27
#define MX_PRESENT_LOAD_L 0x28
#define MX_PRESENT_LOAD_H 0x29
#define MX_PRESENT_VOLTAGE 0x2A
#define MX_PRESENT_TEMPERATURE 0x2B
#define MX_REGISTERED 0x2C
#define MX_MOVING 0x2E
#define MX_LOCK 0x2F
#define MX_PUNCH_L 0x30
#define MX_PUNCH_H 0x31
#define MX_CURRENT_L 0x44
#define MX_CURRENT_H 0x45
#define MX_TORQUE_CONTROL_MODE_ENABLE 0x46
#define MX_GOAL_TORQUE_L 0x47
#define MX_GOAL_TORQUE_H 0x48
#define MX_GOAL_ACCELERATION 0x49
/* MX-64AR Instruction Table */
#define MX_INSTRUCTION_PING 0x01
#define MX_INSTRUCTION_READ_DATA 0x02
#define MX_INSTRUCTION_WRITE_DATA 0x03
#define MX_INSTRUCTION_REG_WRITE 0x04
#define MX_INSTRUCTION_ACTION 0x05
#define MX_INSTRUCTION_RESET 0x06
#define MX_INSTRUCTION_SYNC_WRITE 0x83
/* MX-64AR Conversion Constants */
#define MX_PRESENT_POSITION_DEGREE 0.088
#define MX_PRESENT_SPEED_RPM 0.11
#define MX_PRESENT_LOAD_PERCENT 0.978

/* MX-64AR Commands/Message Parameters Lengths */
#define MX_GOAL_LENGTH 5
#define MX_INSTRUCTION_RESET_LENGTH 2
#define MX_SPEED_LENGTH 5
#define MX_GOAL_SP_LENGTH 7
#define MX_TORQUE_LENGTH 4
#define MX_MT_LENGTH 5
#define MX_POS_LENGTH 4
#define MX_CCW_AL_L 0xFF
#define MX_CCW_AL_H 0x03

/* MX-64AR Modes */
#define MX_MODE_JOINT 0
#define MX_MODE_WHEEL 1
#define MX_MODE_MULTI 2

#endif

